name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Change permissions
        run: chmod 755 docs
      - name: Auto-i18n_translate
        env:
          # 设置环境变量
          ### API BASE:
          CHATGPT_API_BASE: ${{ secrets.CHATGPT_API_BASE }}
          ### API KEY:
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }} #x
        run: |
          pip install -r tools/requirements.txt
          python tools/auto-translater.py || true
      - name: Commit translated
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          git add .
          git commit -a -m "Commit translated" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
      - name: Install MkDocs dependencies
        run: pip install -r requirements.txt
      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force
